# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/PyCQA/isort
    rev: '5.13.2'
    hooks:
    -   id: isort
        entry: isort --diff --check dags tests
        pass_filenames: false
        language_version: python3.12
        always_run: true

-   repo: https://github.com/ambv/black
    rev: '24.8.0'
    hooks:
    - id: black
      name: black
      entry: black --diff --check --color dags tests
      pass_filenames: false
      language_version: python3.12
      always_run: true

-   repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
    -   id: flake8
        additional_dependencies:
            - flake8-pyproject
        entry: flake8 dags tests
        pass_filenames: false
        language_version: python3.12
        always_run: true


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
    -   id: mypy
        # when mypy is run from the pre-commit hook an error occurs due to missing stubs so we need these flags
        entry: mypy --install-types --non-interactive --explicit-package-bases dags tests
        pass_filenames: false
        language_version: python3.12
        always_run: true


