name: CI Workflow

# This workflow runs on both pull requests and pushes to the master branch for tests,
# and on tag creation for the changelog update.
on:
  pull_request:
  push:
    branches: [ master ]
    tags:
      - '*'

# Concurrency settings to manage workflow execution.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# Jobs section begins.
jobs:
  # Build and Test job (runs on pull requests and pushes to master)
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          # install dependencies
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv requirements > requirements.txt --dev
          pip install -r requirements.txt

      - name: Check
        id: check
        run: |
          make check

      - name: Unit Test with pytest
        id: unit_test
        run: |
          pytest -v -s tests/unit --no-header -vv --cov=dags --cov-report=xml --cov-report=term-missing

      - name: Integration Test with pytest
        id: integration-tests
        run: |  
          echo "Running integration tests"


  # Integrity Tests job (runs on pull requests and pushes to master)
  integrity-tests:
    name: Integrity Tests
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          # install dependencies
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv requirements > requirements.txt --dev
          pip install -r requirements.txt

      - name: Prepare Airflow Docker Container
        id: airflow-docker-container
        env:
          CONFIGS_DIR: configs
        run: |
          bash ci_scripts/prepare_airflow_docker_container.sh

      - name: Run Integrity Tests
        id: integrity-tests
        run: |
          pytest -s -v tests/integrity

  # Update Changelog job (runs only when a tag is created)
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          # install dependencies
          python -m pip install --upgrade pip
          pip install jq gh

      - name: Run update_changelog.sh
        run: |
          bash ci_scripts/update_changelog.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}